apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rs-rwt
spec:
  selector:
    matchLabels:
      app: rti-routingservice
  serviceName: "rti-routingservice"
  replicas: 1
  template:
    metadata:
      labels:
        app: rti-routingservice
    spec:
      containers:
      - name: rti-routingservice
        image: kyoungho/rti-routingservice:6.1.0
        ports:
        - containerPort: 7400
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.xml
          subPath: config.xml
        - name: scripts-vol
          mountPath: /mnt/scripts
        env:
        - name: CFG_NAME
          value: "RS-RWT"
        - name: ARGS
          value: "-verbosity 5"
        - name: PUBLIC_IP # value for public ip address
          value: "3.141.238.106"
        - name: PUBLIC_PORT # value for public port 
          value: "30007"
        - name: HOST_PORT # value for host port 
          value: "7400"
        - name: WAN_DOMAIN # value for WAN domain ID
          value: "100"
        - name: LAN_DOMAIN # value for LAN domain ID
          value: "10"
        command: ["/mnt/scripts/run.sh"]
      imagePullSecrets:
        - name: regcred
      volumes: 
        - name: config-volume
          configMap:
            name: routingservice-rwt
        - name: scripts-vol
          configMap:
            name: rs-rwt-init-config
            defaultMode: 0555
